Make changes for RH based systems
Change-Id: Ibbcbb7eeb4b2bacdce13c86d83585ddaebcaf070

diff --git a/etc/init.d/nuage-vpn-agent b/etc/init.d/nuage-vpn-agent
--- a/etc/init.d/nuage-vpn-agent
+++ b/etc/init.d/nuage-vpn-agent
@@ -34,12 +34,20 @@ DAEMON_ARGS="$DAEMON_ARGS --log-file=$LOGFILE"
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 # Load the VERBOSE setting and other rcS variables
-. /lib/init/vars.sh
+[ -f /lib/init/vars.sh ] && . /lib/init/vars.sh
 
 # Define LSB log_* functions.
 # Depend on lsb-base (>= 3.2-14) to ensure that this file is present
 # and status_of_proc is working.
-. /lib/lsb/init-functions
+if [ -f /etc/debian_version ] ; then
+        . /lib/lsb/init-functions
+        OS_START=DEB
+else
+        . /etc/init.d/functions
+        OS_START=RH
+        alias log_daemon_msg=echo
+        alias log_end_msg=echo
+fi
 
 if [ -z "${SYSTEM_USER}" ] ; then
         SYSTEM_USER="root"
@@ -57,18 +65,24 @@ fi
 #
 do_start()
 {
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --background ${STARTDAEMON_CHUID}  --make-pidfile --pidfile $PIDFILE --startas $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --background ${STARTDAEMON_CHUID}  --make-pidfile --pidfile $PIDFILE --startas $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
-	# Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
+    if [ "${OS_START}" = "DEB" ] ; then
+	    # Return
+	    #   0 if daemon has been started
+	    #   1 if daemon was already running
+	    #   2 if daemon could not be started
+	    start-stop-daemon --start --quiet --background ${STARTDAEMON_CHUID}  --make-pidfile --pidfile $PIDFILE --startas $DAEMON --test > /dev/null \
+		    || return 1
+	    start-stop-daemon --start --quiet --background ${STARTDAEMON_CHUID}  --make-pidfile --pidfile $PIDFILE --startas $DAEMON -- \
+		    $DAEMON_ARGS \
+		    || return 2
+	    # Add code here, if necessary, that waits for the process to be ready
+	    # to handle requests from services started subsequently which depend
+	    # on this one.  As a last resort, sleep for some time.
+    else
+        daemon --user ${SYSTEM_USER} --pidfile $PIDFILE "$DAEMON $DAEMON_ARGS &>/dev/null & echo \$! > $PIDFILE"
+        RETVAL="$?"
+        return "$RETVAL"
+    fi
 }
 
 #
@@ -76,38 +90,57 @@ do_start()
 #
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	return "$RETVAL"
+    if [ "${OS_START}" = "DEB" ] ; then
+	    # Return
+	    #   0 if daemon has been stopped
+	    #   1 if daemon was already stopped
+	    #   2 if daemon could not be stopped
+	    #   other if a failure occurred
+	    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	    RETVAL="$?"
+	    [ "$RETVAL" = 2 ] && return 2
+	    # Wait for children to finish too if this is a daemon that forks
+	    # and if the daemon is only ever run from this initscript.
+	    # If the above conditions are not satisfied then add some other code
+	    # that waits for the process to drop all resources that could be
+	    # needed by services started subsequently.  A last resort is to
+	    # sleep for some time.
+	    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	    [ "$?" = 2 ] && return 2
+	    # Many daemons don't delete their pidfiles when they exit.
+	    rm -f $PIDFILE
+	    return "$RETVAL"
+    else
+        killproc -p $PIDFILE $DAEMON
+        RETVAL="$?"
+        return "$RETVAL"
+    fi
 }
 
 #
 # Function that sends a SIGHUP to the daemon/service
 #
 do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-	return 0
+    if [ "${OS_START}" = "DEB" ] ; then
+	    #
+	    # If the daemon can reload its configuration without
+	    # restarting (for example, when it is sent a SIGHUP),
+	    # then implement that here.
+	    #
+	    start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	    return 0
+    else
+        stop
+        start
+    fi
+}
+
+do_status() {
+    if [ "${OS_START}" = "DEB" ] ; then
+        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+    else
+        status -p $PIDFILE $DAEMON && exit 0 || exit $?
+    fi
 }
 
 case "$1" in
@@ -128,7 +161,7 @@ case "$1" in
 	esac
 	;;
   status)
-	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	do_status
 	;;
   #reload|force-reload)
 	#
